### ISSUE TITLE
This is a masterpiece

### ISSUE THREAD

**Issue by turbrider** [ivan-pi/fmetis#6]
I have been sufferred 1 month by the error when I updated my code from metis4 to metis5.  The interface you given in this hub is f**king good. I love you , bro.

**Comment by turbrider** [comment]
> I have been sufferred 1 month by the error when I updated my code from metis4 to metis5. The interface you given in this hub is f**king good. I love you , bro.

I think I should give my error here to make google retrieve this hub.

**Comment by turbrider** [comment]
> I have been sufferred 1 month by the error when I updated my code from metis4 to metis5. The interface you given in this hub is f**king good. I love you , bro.

Hi guys,
 if you sufferred with metis5 with the following error:
Current memory used: 392 bytes
Maximum memory used: 392 bytes
***Memory allocation failed for SetupCtrl: ctrl->tpwgts. Requested size: 10842907309714178088 bytes
with IDXTYPEWIDTH 64 and REALTYPEWIDTH 64
please read this hub carefully, it is really helpful.

**Comment by ivan-pi** [comment]
Glad it helped!

This reminds me I should post this to the METIS forum, so people can find it.
